"""use floats for durations

Revision ID: a022a779868c
Revises: c84ed9caba7c
Create Date: 2025-06-07 17:22:21.449593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a022a779868c'
down_revision = 'c84ed9caba7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prowadzacy', schema=None) as batch_op:
        batch_op.alter_column('domyslny_czas',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('zajecia', schema=None) as batch_op:
        batch_op.alter_column('czas_trwania',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zajecia', schema=None) as batch_op:
        batch_op.alter_column('czas_trwania',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('prowadzacy', schema=None) as batch_op:
        batch_op.alter_column('domyslny_czas',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
