"""Add role and approval fields

Revision ID: c84ed9caba7c
Revises: 
Create Date: 2025-06-07 15:46:31.166079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84ed9caba7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prowadzacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(), nullable=True),
    sa.Column('nazwisko', sa.String(), nullable=True),
    sa.Column('numer_umowy', sa.String(), nullable=True),
    sa.Column('podpis_filename', sa.String(), nullable=True),
    sa.Column('domyslny_czas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uczestnik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie_nazwisko', sa.String(), nullable=True),
    sa.Column('prowadzacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prowadzacy_id'], ['prowadzacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uzytkownik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('haslo_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('prowadzacy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prowadzacy_id'], ['prowadzacy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('zajecia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prowadzacy_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('czas_trwania', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prowadzacy_id'], ['prowadzacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obecnosci',
    sa.Column('zajecia_id', sa.Integer(), nullable=True),
    sa.Column('uczestnik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uczestnik_id'], ['uczestnik.id'], ),
    sa.ForeignKeyConstraint(['zajecia_id'], ['zajecia.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obecnosci')
    op.drop_table('zajecia')
    op.drop_table('uzytkownik')
    op.drop_table('uczestnik')
    op.drop_table('prowadzacy')
    # ### end Alembic commands ###
